
import { Report } from '../types';

const STORAGE_KEY = 'report_master_data_v1';

const getTodayStr = () => new Date().toISOString().split('T')[0];

const PREBUILT_MODELS: Report[] = [
  {
    id: 'MOV-PNEUS',
    createdAt: Date.now() + 1000,
    category: 'MÓVEL',
    isTemplate: true,
    omDescription: 'MP MONIT PNEUS',
    activityExecuted: '✅ Foi preenchido todas as documentações\n✅ Realizado Bloqueio do equipamento\n✅ Foi realizada a limpeza do mems\n✅ Inspecionado e realizado limpeza das antenas Wi-fi e 3G.\n✅ Foram verificados todos os conectores e realizado o reaperto dos MEMS, e limpeza.\n✅ Verificado a integridade dos cabos das antenas ativas.\n✅ Verificado fixação e integridade dos chicotes dos conectores.\n✅ VALIDACAO OK',
    date: getTodayStr(),
    omNumber: '',
    equipment: '',
    location: '',
    activityType: 'preventiva',
    startTime: '',
    endTime: '',
    iamoDeviation: false,
    iamoExplanation: '',
    isOmFinished: true,
    hasPendencies: false,
    pendencyExplanation: '',
    observations: '',
    teamShift: 'A',
    workCenter: 'SC108HH',
    technicians: '',
    photos: []
  },
  {
    id: 'MOV-RADIO-CPE',
    createdAt: Date.now() + 500,
    category: 'MÓVEL',
    isTemplate: true,
    omDescription: 'MP RADIO CPE',
    activityExecuted: '✅ Foi preenchido toda documentação, bloqueado o equipamento.\n✅ Foi Inspecionar fonte de alimentação do Rádio AVI.\n✅ Realizado os testes\n✅ Feito organização dos cabo Extensor\n✅ Verificado alimentação de 24 volts\n✅ Foi verificado todos os conectores\n✅ Foi verificado se cabeamento apresentar algum desgaste\n✅ Verificado os fusiveis\n✅ Foi verificado conexões de Ethernet do Rádio\n✅ Foi verificado folga na fixação antena\n✅ Verificado instalação cada antena Feito limpeza externa das antenas.\n✅ 5S\n✅ Feito a validação fisicamente e remotamente',
    date: getTodayStr(),
    omNumber: '',
    equipment: '',
    location: '',
    activityType: 'preventiva',
    startTime: '',
    endTime: '',
    iamoDeviation: false,
    iamoExplanation: '',
    isOmFinished: true,
    hasPendencies: false,
    pendencyExplanation: '',
    observations: '',
    teamShift: 'B',
    workCenter: 'SC108HH',
    technicians: '',
    photos: []
  },
  {
    id: 'RAJ-OVERLAND',
    createdAt: Date.now(),
    category: 'FIXO',
    isTemplate: true,
    omDescription: 'VALIDAÇÃO LOGICA RAJANTS - OVERLAND',
    activityExecuted: '✅ Acessar bccomander\n✅ Verificar os parametros\n✅ Custos dos peers\n✅ Link state change',
    date: getTodayStr(),
    omNumber: '',
    equipment: 'MP VALIDAÇÃO LOGICA RAJANTS OVERLAND',
    location: 'OVERLAND',
    activityType: 'preventiva',
    startTime: '',
    endTime: '',
    iamoDeviation: false,
    iamoExplanation: '',
    isOmFinished: true,
    hasPendencies: false,
    pendencyExplanation: '',
    observations: '',
    teamShift: 'B',
    workCenter: 'SC108HH',
    technicians: '',
    photos: []
  },
  {
    id: 'RAJ-5LINHA',
    createdAt: Date.now() - 1000,
    category: 'FIXO',
    isTemplate: true,
    omDescription: 'VALIDAÇÃO LOGICA RAJANTS - 5ª LINHA',
    activityExecuted: '✅ Acessar bccomander\n✅ Verificar os parametros\n✅ Custos dos peers\n✅ Link state change',
    date: getTodayStr(),
    omNumber: '',
    equipment: 'MP VALIDAÇÃO LOGICA RAJANTS 5ª LINHA',
    location: '5ª LINHA',
    activityType: 'preventiva',
    startTime: '',
    endTime: '',
    iamoDeviation: false,
    iamoExplanation: '',
    isOmFinished: true,
    hasPendencies: false,
    pendencyExplanation: '',
    observations: '',
    teamShift: 'B',
    workCenter: 'SC108HH',
    technicians: '',
    photos: []
  },
  {
    id: 'RAJ-S1',
    createdAt: Date.now() - 2000,
    category: 'FIXO',
    isTemplate: true,
    omDescription: 'VALIDAÇÃO LOGICA RAJANTS - SISTEMA 1',
    activityExecuted: '✅ Acessar bccomander\n✅ Verificar os parametros\n✅ Custos dos peers\n✅ Link state change',
    date: getTodayStr(),
    omNumber: '',
    equipment: 'MP VALIDAÇÃO LOGICA RAJANTS S1',
    location: 'SISTEMA 1',
    activityType: 'preventiva',
    startTime: '',
    endTime: '',
    iamoDeviation: false,
    iamoExplanation: '',
    isOmFinished: true,
    hasPendencies: false,
    pendencyExplanation: '',
    observations: '',
    teamShift: 'B',
    workCenter: 'SC108HH',
    technicians: '',
    photos: []
  },
  {
    id: 'RAJ-S2',
    createdAt: Date.now() - 3000,
    category: 'FIXO',
    isTemplate: true,
    omDescription: 'VALIDAÇÃO LOGICA RAJANTS - SISTEMA 2',
    activityExecuted: '✅ Acessar bccomander\n✅ Verificar os parametros\n✅ Custos dos peers\n✅ Link state change',
    date: getTodayStr(),
    omNumber: '',
    equipment: 'MP VALIDAÇÃO LOGICA RAJANTS S2',
    location: 'SISTEMA 2',
    activityType: 'preventiva',
    startTime: '',
    endTime: '',
    iamoDeviation: false,
    iamoExplanation: '',
    isOmFinished: true,
    hasPendencies: false,
    pendencyExplanation: '',
    observations: '',
    teamShift: 'B',
    workCenter: 'SC108HH',
    technicians: '',
    photos: []
  },
  {
    id: 'RAJ-S3',
    createdAt: Date.now() - 4000,
    category: 'FIXO',
    isTemplate: true,
    omDescription: 'VALIDAÇÃO LOGICA RAJANTS - SISTEMA 3',
    activityExecuted: '✅ Acessar bccomander\n✅ Verificar os parametros\n✅ Custos dos peers\n✅ Link state change',
    date: getTodayStr(),
    omNumber: '',
    equipment: 'MP VALIDAÇÃO LOGICA RAJANTS S3',
    location: 'SISTEMA 3',
    activityType: 'preventiva',
    startTime: '',
    endTime: '',
    iamoDeviation: false,
    iamoExplanation: '',
    isOmFinished: true,
    hasPendencies: false,
    pendencyExplanation: '',
    observations: '',
    teamShift: 'B',
    workCenter: 'SC108HH',
    technicians: '',
    photos: []
  },
  {
    id: 'RAJ-S4',
    createdAt: Date.now() - 5000,
    category: 'FIXO',
    isTemplate: true,
    omDescription: 'VALIDAÇÃO LOGICA RAJANTS - SISTEMA 4',
    activityExecuted: '✅ Acessar bccomander\n✅ Verificar os parametros\n✅ Custos dos peers\n✅ Link state change',
    date: getTodayStr(),
    omNumber: '',
    equipment: 'MP VALIDAÇÃO LOGICA RAJANTS S4',
    location: 'SISTEMA 4',
    activityType: 'preventiva',
    startTime: '',
    endTime: '',
    iamoDeviation: false,
    iamoExplanation: '',
    isOmFinished: true,
    hasPendencies: false,
    pendencyExplanation: '',
    observations: '',
    teamShift: 'B',
    workCenter: 'SC108HH',
    technicians: '',
    photos: []
  },
  {
    id: 'FIX-REDUNDANCIA',
    createdAt: Date.now() - 6000,
    category: 'FIXO',
    isTemplate: true,
    omDescription: 'MP INSPEÇÃO DE REDE DE REDUNDÂNCIA',
    activityExecuted: '✅ Verificar indicação dos leds dos ozds, observando se as redundancias dos canais ch02 e ch3 estão ativo\n✅ Verificar condições de dio\'s e cordões\n✅ Verificar fixação e regulagem dos cabos\n✅ Verificar integridade dos cabos\n✅ Verificar conectores\n✅ Abrir nota em caso de anormalidade\n✅ Desmobilização e 5s',
    date: getTodayStr(),
    omNumber: '',
    equipment: '',
    location: '',
    activityType: 'preventiva',
    startTime: '',
    endTime: '',
    iamoDeviation: false,
    iamoExplanation: '',
    isOmFinished: true,
    hasPendencies: false,
    pendencyExplanation: '',
    observations: '',
    teamShift: 'B',
    workCenter: 'SC108HH',
    technicians: '',
    photos: []
  },
  {
    id: 'FIX-RADIO-RAJAT',
    createdAt: Date.now() - 7000,
    category: 'FIXO',
    isTemplate: true,
    omDescription: 'MP RADIO RAJAT',
    activityExecuted: '✅ Verificar e registrar nivel sinal enlace\n✅ Verificar e registrar SNR\n✅ Verificar e registrar canal\n✅ Verificar visada\n✅ Corrigir desvios cabo coaxial e conectores\n✅ Verificar cabos e conexoes do painel\n✅ Verificar energia e proteções\n✅ Limpeza interna/externa painel\n✅ Verificar vedação e identificação',
    date: getTodayStr(),
    omNumber: '',
    equipment: '',
    location: '',
    activityType: 'preventiva',
    startTime: '',
    endTime: '',
    iamoDeviation: false,
    iamoExplanation: '',
    isOmFinished: true,
    hasPendencies: false,
    pendencyExplanation: '',
    observations: '',
    teamShift: 'B',
    workCenter: 'SC108HH',
    technicians: '',
    photos: []
  },
  {
    id: 'FIX-LIMPEZA-ATIVOS',
    createdAt: Date.now() - 8000,
    category: 'FIXO',
    isTemplate: true,
    omDescription: 'MP LIMPEZA DE ATIVOS',
    activityExecuted: '✅ Checar controle de acesso\n✅ Limpeza externa/interna e componentes\n✅ Checar vedação do painel\n✅ Reaperto das conexoes (Rede, Alimentação, Profibus)\n✅ Checar link principal e falha nos cartoes\n✅ Organizar e identificar cabos\n✅ Checar fonte (24V)\n✅ Conferir aterramento e iluminação',
    date: getTodayStr(),
    omNumber: '',
    equipment: '',
    location: '',
    activityType: 'preventiva',
    startTime: '',
    endTime: '',
    iamoDeviation: false,
    iamoExplanation: '',
    isOmFinished: true,
    hasPendencies: false,
    pendencyExplanation: '',
    observations: '',
    teamShift: 'A',
    workCenter: 'SC108HH',
    technicians: '',
    photos: []
  },
  {
    id: 'FIX-FONTE-RAJANT',
    createdAt: Date.now() - 9000,
    category: 'FIXO',
    isTemplate: true,
    omDescription: 'FIXAR FONTE RAJANT',
    activityExecuted: '✅ Fazer procedimentos de segurança\n✅ Preparar ferramentas e materiais\n✅ Realizar bloqueio do equipamento\n✅ Realizar teste\n✅ Limpar local da tarefa\n✅ Retirar bloqueio do equipamento\n✅ Descartar residuos gerados\n✅ Apropriar mão de obra',
    date: getTodayStr(),
    omNumber: '',
    equipment: '',
    location: '',
    activityType: 'preventiva',
    startTime: '',
    endTime: '',
    iamoDeviation: false,
    iamoExplanation: '',
    isOmFinished: true,
    hasPendencies: false,
    pendencyExplanation: '',
    observations: '',
    teamShift: 'B',
    workCenter: 'SC108HH',
    technicians: 'Luiz Gustavo / Rafael',
    photos: []
  },
  {
    id: 'FIX-TAG-SW',
    createdAt: Date.now() - 10000,
    category: 'FIXO',
    isTemplate: true,
    omDescription: 'REALIZAR FIXAÇÃO DE TAG DEFINITIVO NO SW',
    activityExecuted: '✅ Fazer procedimentos de segurança\n✅ Preparar ferramentas e materiais\n✅ Realizar limpeza geral do pl\n✅ Confeccionar e instalar tag\n✅ Apropriar mão de obra',
    date: getTodayStr(),
    omNumber: '',
    equipment: '',
    location: '',
    activityType: 'preventiva',
    startTime: '',
    endTime: '',
    iamoDeviation: false,
    iamoExplanation: '',
    isOmFinished: true,
    hasPendencies: false,
    pendencyExplanation: '',
    observations: '',
    teamShift: 'B',
    workCenter: 'SC108HH',
    technicians: 'Luiz Gustavo / Rafael',
    photos: []
  },
  {
    id: 'FIX-TRAVA-DIN',
    createdAt: Date.now() - 11000,
    category: 'FIXO',
    isTemplate: true,
    omDescription: 'INSTALAR TRAVA TRILHO DIN',
    activityExecuted: '✅ Preenchido toda a documentação\n✅ Checado controle de acesso\n✅ Verificado cenário da atividade\n✅ Realizado instalação das travas\n✅ Desmobilização e 5s',
    date: getTodayStr(),
    omNumber: '',
    equipment: '',
    location: '',
    activityType: 'preventiva',
    startTime: '',
    endTime: '',
    iamoDeviation: false,
    iamoExplanation: '',
    isOmFinished: true,
    hasPendencies: false,
    pendencyExplanation: '',
    observations: '',
    teamShift: 'B',
    workCenter: 'SC108HH',
    technicians: '',
    photos: []
  },
  {
    id: 'FIX-PREV-SW',
    createdAt: Date.now() - 12000,
    category: 'FIXO',
    isTemplate: true,
    omDescription: 'PREVEN. LOGICA SWITCH SW0663',
    activityExecuted: '✅ Verificar/Adicionar Banner\n✅ Descrição das portas\n✅ Acesso via TACACS\n✅ SSH Ativo\n✅ Desativar POE desnecessário\n✅ Analisar logs de falhas\n✅ Teste transceiver (redundância)\n✅ Revisão de configurações padrões',
    date: getTodayStr(),
    omNumber: '',
    equipment: '',
    location: '',
    activityType: 'preventiva',
    startTime: '',
    endTime: '',
    iamoDeviation: false,
    iamoExplanation: '',
    isOmFinished: true,
    hasPendencies: false,
    pendencyExplanation: '',
    observations: '',
    teamShift: 'B',
    workCenter: 'SC108HH',
    technicians: '',
    photos: []
  },
  {
    id: 'FIX-LIMPEZA-PAINEL',
    createdAt: Date.now() - 13000,
    category: 'FIXO',
    isTemplate: true,
    omDescription: 'REALIZAR LIMPEZA E ORGANIZAÇÃO DO PAINEL',
    activityExecuted: '✅ Procedimentos de segurança\n✅ Bloqueio de equipamento\n✅ Limpeza geral do PL\n✅ Organizar cabos\n✅ Espuma expansiva nas aberturas\n✅ Desmobilização e 5s',
    date: getTodayStr(),
    omNumber: '',
    equipment: '',
    location: '',
    activityType: 'preventiva',
    startTime: '',
    endTime: '',
    iamoDeviation: false,
    iamoExplanation: '',
    isOmFinished: true,
    hasPendencies: false,
    pendencyExplanation: '',
    observations: '',
    teamShift: 'B',
    workCenter: 'SC108HH',
    technicians: '',
    photos: []
  },
  {
    id: 'FIX-LOGICA-CFTV',
    createdAt: Date.now() - 14000,
    category: 'FIXO',
    isTemplate: true,
    omDescription: 'MP LOGICA CFTV',
    activityExecuted: '✅ Câmeras ativas no sistema\n✅ Cadastrada no Zabbix/Netbox/CMDB\n✅ Credenciais de automação\n✅ Hostname conforme TAG\n✅ Máscara/Gateway/SNMP\n✅ Resolução e Nitidez\n✅ Verificação de Gravações (7 dias)\n✅ Comandos PTZ (se aplicável)',
    date: getTodayStr(),
    omNumber: '',
    equipment: '',
    location: '',
    activityType: 'preventiva',
    startTime: '',
    endTime: '',
    iamoDeviation: false,
    iamoExplanation: '',
    isOmFinished: true,
    hasPendencies: false,
    pendencyExplanation: '',
    observations: '',
    teamShift: 'B',
    workCenter: 'SC108HH',
    technicians: '',
    photos: []
  }
];

export const storage = {
  getReports: (): Report[] => {
    const data = localStorage.getItem(STORAGE_KEY);
    if (!data) {
      storage.saveReports(PREBUILT_MODELS);
      return PREBUILT_MODELS;
    }
    return JSON.parse(data);
  },
  
  saveReports: (reports: Report[]) => {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(reports));
  },

  addReport: (report: Report) => {
    const reports = storage.getReports();
    reports.unshift(report);
    storage.saveReports(reports);
  },

  updateReport: (updatedReport: Report) => {
    const reports = storage.getReports();
    const index = reports.findIndex(r => r.id === updatedReport.id);
    if (index !== -1) {
      reports[index] = updatedReport;
      storage.saveReports(reports);
    }
  },

  deleteReport: (id: string) => {
    const reports = storage.getReports();
    const filtered = reports.filter(r => r.id !== id);
    storage.saveReports(filtered);
  }
};
